PACKAGE = drcl.inet

SOURCE  = \
		CoreServiceLayer.java \
		CoreServiceLayerBeanInfo.java \
		CSLBuilder.java \
		InetConstants.java \
		InetPacket.java \
		InetUtil.java \
		Link.java \
		Network.java \
		Node.java \
		NodeBeanInfo.java \
		NodeBuilder.java \
		Protocol.java \
		TclComponent.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
